# Generated by Django 2.1.4 on 2019-10-03 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
